/****** Object:  Database [managesale]    Script Date: 4/6/2023 12:10:22 AM ******/
CREATE DATABASE [managesale]  (EDITION = 'GeneralPurpose', SERVICE_OBJECTIVE = 'GP_S_Gen5_1', MAXSIZE = 1 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [managesale] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [managesale] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [managesale] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [managesale] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [managesale] SET ARITHABORT OFF 
GO

ALTER DATABASE [managesale] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [managesale] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [managesale] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [managesale] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [managesale] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [managesale] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [managesale] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [managesale] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [managesale] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [managesale] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [managesale] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [managesale] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [managesale] SET  MULTI_USER 
GO

ALTER DATABASE [managesale] SET ENCRYPTION ON
GO

ALTER DATABASE [managesale] SET QUERY_STORE = ON
GO

ALTER DATABASE [managesale] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
GO

ALTER DATABASE [managesale] SET  READ_WRITE 
GO

